// app/layout.jsx

import './globals.css';
import { Geist, Geist_Mono } from 'next/font/google';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Your Site Title',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <head>
        {/* ✅ D-ID Agent Script as raw HTML script */}
        <script
          type="module"
          src="https://agent.d-id.com/v2/index.js"
          data-mode="fabio"
          data-client-key="Z29vZ2xlLW9hdXRoMnwxMDU5NjcyNDAwMjI0MjgyNDc2NTg6MjY3SzVKUFg5VU5iUTdCdmZpUnNN"
          data-agent-id="v2_agt_e3FkINM7"
          data-name="did-agent"
          data-monitor="true"
          data-orientation="horizontal"
          data-position="right"
        ></script>
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
